### ISSUE TITLE
How to change to language other than English

### ISSUE THREAD

**Issue by sin2akshay** [Lysozyme/garena-lol-english#1]
I am playing on Garena Singapore server and my game is already in English. I want to explore the voice lines of heroes in another language. Is it possible to change from English to another language using your script?

**Comment by Lysozyme** [comment]
Hi,

Unfortunately that's not possible with my script.

Here's how this script works: when the game is launched in a non-English locale (e.g. zh_TW), the script changes that to en_US and relaunches the game.
This works because the Garena client contains both Chinese and English files.

However, when you try to relaunch the game using something like ja_JP, the result is imperfect.
Some text will become Japanese, some text will become English, and more importantly, the voice stays English.
This is because the Garena client does NOT contain all Japanese localized files.
I haven't tried all languages, but ko_KR etc. will probably cause the same issues.

In order to change the client to other languages (that the Garena client doesn't contain by default),
I think you'll need to do something like (1) download the Japanese version from Riot client (2) copy or maybe overwrite Japanese files from Riot client to Garena client.
However, I can't really give you advices on this since I haven't tried it myself.
